environment:
  matrix:
  - TARGET: i686-pc-windows-msvc
  - TARGET: x86_64-pc-windows-msvc

install:
  # Install rust, x86_64-pc-windows-msvc host
  - appveyor-retry appveyor DownloadFile https://win.rustup.rs/ -FileName rustup-init.exe
  - rustup-init.exe -y --default-host x86_64-pc-windows-msvc
  - set PATH=%PATH%;C:\Users\appveyor\.cargo\bin
  # Install the target we're compiling for
  - if NOT "%TARGET%" == "x86_64-pc-windows-msvc" rustup target add %TARGET%
  - rustc -vV
  - cargo -vV
  - git submodule update --init

build: false

test_script:
  - cargo test --target %TARGET%

